config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
    
    resources :articles
    
    root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    
    def new
    end
    
  def show
    @article = Article.find(params[:id])
  end
 
    
    
def create
  @article = Article.new(article_params)
 
  @article.save
  redirect_to @article
end
    
    
def destroy
  @article = Article.find(params[:id])
  @article.destroy
 
  redirect_to articles_path
end
    
    
 def youtube_id
     
     @article.title = @song
     
    YouTubeAddy.extract_video_id(@song.url)
  end
 
private
  def article_params
    params.require(:article).permit(:title, :text)
  end
    
    
    
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artciles_helper.rb
module ArtcilesHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/new.html.erb
<h1>Video Link</h1>

<%= form_with scope: :article, url: articles_path, local: true do |form| %>
  <p>
    <%= form.label "Enter Link Below", class: 'small'%><br>
    <%= form.text_field :title, class: 'small' %>
  </p>
 
  <p>
    <%= form.submit "Submit Link"%>
  </p>
<% end %>

<%= link_to 'Back', welcome_index_path, class: 'small' %>

app/views/articles/show.html.erb
 
<<iframe src= 'https://www.youtube.com/embed/<%= @article.title %>' frameborder='0'></iframe>


<%= link_to 'Back', welcome_index_path, class: 'small' %>

<!--
<iframe src= 'https://www.youtube.com/embed/videoseries?list=<%= @article.title %>' frameborder='0'></iframe>



<iframe src= 'https://www.youtube.com/embed/videoseries?list=<%= @youtube_id %>' frameborder='0'></iframe>

<P> <%= @youtube_id %> </P>

-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VideoLinker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
 <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>    
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>
  <span>oediv</span>
  <span>Embedder</span>
</h1>
<p><%= link_to "<Add Link Here>", new_article_path, class="small" %>
    <p class="small">© @deliciousgammon 2019</p>